//auth
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// CONDITIONS
export const CONDITIONS = "CONDITIONS";
export const USER_CONDITIONS = "USER_CONDITIONS";
export const SET_CONDITIONS = "SET_CONDITIONS";
export const DELETE_CONDITIONS = "DELETE_CONDITIONS";

// MEDICATIONS
export const MEDICATIONS = "MEDICATIONS";
