//auth
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// CONDITIONS
export const CONDITIONS = "CONDITIONS";

// MEDICATIONS
export const MEDICATIONS = "MEDICATIONS";
export const SET_PATIENT_MEDICATIONS = "SET_PATIENT_MEDICATIONS"
